services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: tasktracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev
    ports:
      - "5433:5432" ## 5432 is the port inside container while 5433 is the port for pc
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
